version: '2.4'

services:
  locator:
    image: apachegeode/geode
    hostname: locator
    mem_limit: 512m
    expose:
     - "10334"
     - "1099"
     - "7575"
     - "7070"
    ports:
     - "1099:1099"
     - "${LOCATOR_PORT}:10334"
     - "7575:7575"
     - "7070:7070"
    command:
      - bash
      - -c 
      - |
        gfsh start locator --name=`hostname` --mcast-port=0 \
            --hostname-for-clients=${HOSTNAME_FOR_CLIENTS} \
        && \
        while true; do
           sleep 10
        done
