  ${SERVER_NAME}:
    image: apachegeode/geode
    hostname: ${SERVER_NAME}
    mem_limit: 1g
    depends_on:
     - locator
    expose:
     - "8080"
     - "${SERVER_PORT}"
     - "1099"
    ports:
     - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
     - ./geode-addon:/geode-addon/
    command:
      - bash
      - -c 
      - |
        if [ ! -d /run ]; then mkdir /run; fi \
        && \
        gfsh start server \
            --name=`hostname` \
            --locators=locator[$LOCATOR_PORT] \
            --dir=/run \
            --initial-heap=$MIN_HEAP_SIZE \
            --max-heap=$MAX_HEAP_SIZE \
            --hostname-for-clients=$HOSTNAME_FOR_CLIENTS \
            --classpath=/geode-addon/lib/*:/geode-addon/plugins/* \
            --cache-xml-file=/geode-addon/etc/cache.xml \
            --J=-Dgeode-addon.server.port=${SERVER_PORT} \
        && \
        while true; do
           sleep 10
        done
    restart: on-failure
