#!/usr/bin/env bash 

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-tree -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - List all the root environments initialized by 'init_addon'

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Lists all the root environments initialized by 'init_addon'. 
   
DEFAULT
   $EXECUTABLE

SEE ALSO
EOF
   printSeeAlsoList "list_*" $EXECUTABLE
   exit
fi

if [ "$GEODE_ADDON_WORKSPACES_HOME" == "" ]; then
   echo "ERROR: Workspaces not initialized. Please first run 'init_addon' to initialize workspaces."
   echo "       Command aborted."
   exit 1
fi
if [ ! -d "$GEODE_ADDON_WORKSPACES_HOME" ]; then
   echo "ERROR: Invalid workspaces. Please run 'init_addon' to initialize workspaces."
   echo "       Command aborted."
   exit 1
fi

PARENT_DIR="$(dirname "$GEODE_ADDON_WORKSPACES_HOME")"

ROOTS=""
ROOT_DIRS=`ls $PARENT_DIR`
pushd $PARENT_DIR > /dev/null 2>&1
for i in $ROOT_DIRS; do
if [ -f "$i/initenv.sh" ] && [ -f "$i/.addonenv.sh" ] && [ -f "$i/setenv.sh" ]; then
 if [ "$ROOTS" == "" ]; then
    ROOTS="$i"
 else
    ROOTS="$ROOTS $i"
 fi
fi
done
popd > /dev/null 2>&1
echo "$ROOTS"
