#!/usr/bin/env bash

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-java -geode -vm -key -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

#
# Determeint $TAR_BALL_PATH
#
ROOT_DIR_NAME=$(basename $BASE_DIR)
TOP_DIR="$(dirname "$BASE_DIR")"
TAR_BALL_GZ_NAME=$ROOT_DIR_NAME.tar.gz
TAR_BALL_GZ_PATH=$BASE_DIR/bundles/$TAR_BALL_GZ_NAME

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $GEODE_ADDON_WORKSPACE

NAME
   $EXECUTABLE - Install Geode/GemFire and Java remotely on the workspace VMs

SYNOPSIS
   $EXECUTABLE [-vm comma_separated_hosts] [-key private_key_file] 
               [-java jdk_distribution_file]
               [-geode imdg_or_jet_distribution_file]
               [-?]

DESCRIPTION
  Installs the specified Geode and/or Java remotely on the workspace VMs.

  If the '-vm' option is not specified, then it installs the specified file(s) to
  the hosts defined by the VM_HOSTS environment variable in the workspace 'setenv.sh'
  file.

OPTIONS

    -vm comma_separated_hosts
              A list of VM hosts or addresses separated by comma. Spaces NOT allowed.

    -key private_key_file
              Private key file path. To ssh into your VM such as ones on AWS, you may
              supply your private key file. Normally, the private key file is not
              required if you have set public-key authentication.

    -java java_distribution_file
              JDK distribution file, e.g. jdk-8u212-linux-x64.tar.gz

    -geode imdg_or_jet_distribution_file
              Geode distribution file, e.g. geode-enterprise-3.12.5.tar.gz.

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE -cluster $CLUSTER file_path
EOF
fi
cat <<EOF

SEE ALSO
EOF
   printSeeAlsoList "vm_*" $EXECUTABLE
   exit
fi

# Replace , with space
__VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
DEFAULT_USER=$(whoami)
VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`

if [ "$KEY" == "" ]; then
   KEY=`getClusterProperty "vm.privateKeyFile"`
fi
VM_KEY=""
if [ "$KEY" != "" ]; then 
   if [ ! -f "$KEY" ]; then
      echo >&2 "ERROR: Specified private key does not exist [$KEY]."
      echo >&2 "       Command aborted."
      exit 1
   fi
   VM_KEY="-i $KEY"
fi

# Determine all VMs that do not have Java and Geode installed.
JAVA_HOME_COMMAND="if [ -d "$VM_JAVA_HOME" ]; then echo true; else echo false; fi"
GEODE_HOME_COMMAND="if [ -d "$VM_GEODE_HOME" ]; then echo true; else echo false; fi"
JAVA_HOME_NOT_FOUND_LIST=""
GEODE_HOME_NOT_FOUND_LIST=""
for VM_HOST in $__VM_HOSTS; do
   JAVA_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$JAVA_HOME_COMMAND")
   GEODE_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$GEODE_HOME_COMMAND")
   if [ "$JAVA_HOME_EXISTS" == "false" ]; then
      JAVA_HOME_NOT_FOUND_LIST="$JAVA_HOME_NOT_FOUND_LIST $VM_HOST"
   fi
   if [ "$GEODE_HOME_EXISTS" == "false" ]; then
      GEODE_HOME_NOT_FOUND_LIST="$GEODE_HOME_NOT_FOUND_LIST $VM_HOST"
   fi
done

echo ""
# Install Java
if [ "$JAVA_HOME_ARG" != "" ]; then
   if [ ! -f "$JAVA_HOME_ARG" ]; then
      echo >&2 "ERROR: Invalid path [$JAVA_HOME_ARG]."
      echo >&2 "       Command aborted."
      exit 1
   fi
   JAVA_DIST_FILE_NAME=$(basename $JAVA_HOME_ARG)
   JAVA_PARENT_PATH="$(dirname "$VM_JAVA_HOME")"
   echo "$JAVA_DIST_FILE_NAME"
   if [ "$JAVA_HOME_NOT_FOUND_LIST" != "" ]; then
      for VM_HOST in $JAVA_HOME_NOT_FOUND_LIST; do
         echo "   Installing $VM_HOST..."
         scp -q -r $VM_KEY $JAVA_HOME_ARG $VM_USER@$VM_HOST:/tmp/
         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $JAVA_PARENT_PATH/ -xzf /tmp/$JAVA_DIST_FILE_NAME; rm /tmp/$JAVA_DIST_FILE_NAME"
      done
      echo "   Java installation complete."
   else
      echo "   Java already installed on all VMs."
   fi
   echo ""
fi

# Install Geode
if [ "$GEODE_ARG" != "" ]; then
   if [ ! -f "$GEODE_ARG" ]; then
      echo >&2 "ERROR: Invalid path [$GEODE_ARG]."
      echo >&2 "       Command aborted."
      exit 1
   fi
   GEODE_DIST_FILE_NAME=$(basename $GEODE_ARG)
   GEODE_PARENT_PATH="$(dirname "$VM_GEODE_HOME")"
   echo "$GEODE_DIST_FILE_NAME"
   if [ "$GEODE_HOME_NOT_FOUND_LIST" != "" ]; then
      for VM_HOST in $GEODE_HOME_NOT_FOUND_LIST; do
         echo "   Installing $VM_HOST..."
         scp -q -r $VM_KEY $GEODE_ARG $VM_USER@$VM_HOST:/tmp/
         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $GEODE_PARENT_PATH/ -xzf /tmp/$GEODE_DIST_FILE_NAME; rm /tmp/$GEODE_DIST_FILE_NAME"
      done
      echo "   Geode installation complete."
   else
      echo "   Geode already installed on all VMs."
   fi
fi

echo ""
echo "Run 'vm_test' to check installation and configuration status."
echo ""
